require:
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lib/tasks/static.rake

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
